twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        project_name: '%project_name%'
        possible_locales: '%possible_locales%'
        kingdom_extension_settings: '%kingdom_extension_settings%'
